CREATE DATABASE netflix;
USE netflix;
CREATE TABLE movies (
id INT NOT NULL AUTO_INCREMENT, 
title VARCHAR(45) NOT NULL,
genre VARCHAR(45) NOT NULL,
image TEXT NOT NULL,
category VARCHAR(45) NOT NULL,
`year` INT,
PRIMARY KEY (id));
