CREATE DATABASE netflix;
USE netflix;

CREATE TABLE movies (
id INT NOT NULL AUTO_INCREMENT, 
title VARCHAR(45) NOT NULL,
genre VARCHAR(45) NOT NULL,
image TEXT NOT NULL,
category VARCHAR(45) NOT NULL,
`year` INT,
PRIMARY KEY (id));

CREATE TABLE users(
idUser INT NOT NULL AUTO_INCREMENT,
`user` VARCHAR(45) NOT NULL,
`password` VARCHAR(45) NOT NULL,
`name` VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
plan_details VARCHAR(45) NOT NULL,
PRIMARY KEY (idUser));

CREATE TABLE actors(
idActor INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(45) NOT NULL,
lastname VARCHAR (45) NOT NULL,
country VARCHAR(45) NOT NULL,
year_birthday INT,
PRIMARY KEY (idActor));
